import { Routes } from '@angular/router';
import { ChartsConfigurationAnimationDemo } from './configuration/animation';
import { ChartsConfigurationAnnotationDemo } from './configuration/annotation';
import { ChartsConfigurationAxesDemo } from './configuration/axes';
import { ChartsConfigurationDataLabelsDemo } from './configuration/data-labels';
import { ChartsConfigurationDecimationDemo } from './configuration/decimation';
import { ChartsConfigurationExportDemo } from './configuration/export';
import { ChartsConfigurationHoverDemo } from './configuration/hover';
import { ChartsConfigurationLegendDemo } from './configuration/legend';
import { ChartsConfigurationNavigatorDemo } from './configuration/navigator';
import { ChartsConfigurationPluginsDemo } from './configuration/plugins';
import { ChartsConfigurationReferenceLinesBandsDemo } from './configuration/reference-lines-bands';
import { ChartsConfigurationTitleCaptionDemo } from './configuration/title-caption';
import { ChartsConfigurationTooltipDemo } from './configuration/tooltip';
import { ChartsConfigurationZoomPanDemo } from './configuration/zoom-pan';
import { ChartsGettingStartedArchitectureDemo } from './getting-started/architecture';
import { ChartsGettingStartedLlmsDemo } from './getting-started/llms';
import { ChartsGettingStartedSetupDemo } from './getting-started/setup';
import { ChartsInternationalizationLocaleDemo } from './internationalization/locale';
import { ChartsInternationalizationRtlDemo } from './internationalization/rtl';
import { ChartsReferenceAccessibilityDemo } from './reference/accessibility';
import { ChartsReferenceApiDemo } from './reference/api';
import { ChartsReferencePerformanceDemo } from './reference/performance';
import { ChartsReferenceResponsiveDemo } from './reference/responsive';
import { ChartsReferenceThemingDemo } from './reference/theming';
import { ChartsReferenceTreeShakingDemo } from './reference/tree-shaking';
import { ChartsTypesCandlestickDemo } from './types/candlestick';
import { ChartsTypesCandlestickCandlestickDemo } from './types/candlestick/candlestick';
import { ChartsTypesCandlestickHollowDemo } from './types/candlestick/hollow';
import { ChartsTypesCandlestickLiveDataDemo } from './types/candlestick/live-data';
import { ChartsTypesCandlestickOhlcDemo } from './types/candlestick/ohlc';
import { ChartsTypesCandlestickPlaygroundDemo } from './types/candlestick/playground';
import { ChartsTypesColumnBarDemo } from './types/column-bar';
import { ChartsTypesColumnBarBarDemo } from './types/column-bar/bar';
import { ChartsTypesColumnBarGroupedDemo } from './types/column-bar/grouped';
import { ChartsTypesColumnBarPlaygroundDemo } from './types/column-bar/playground';
import { ChartsTypesColumnBarStackedDemo } from './types/column-bar/stacked';
import { ChartsTypesColumnBarWaterfallDemo } from './types/column-bar/waterfall';
import { ChartsTypesComboDemo } from './types/combo';
import { ChartsTypesComboExamplesDemo } from './types/combo/examples';
import { ChartsTypesHeatmapDemo } from './types/heatmap';
import { ChartsTypesHeatmapHeatmapDemo } from './types/heatmap/heatmap';
import { ChartsTypesHeatmapPlaygroundDemo } from './types/heatmap/playground';
import { ChartsTypesLineAreaDemo } from './types/line-area';
import { ChartsTypesLineAreaAreaDemo } from './types/line-area/area';
import { ChartsTypesLineAreaLineDemo } from './types/line-area/line';
import { ChartsTypesLineAreaPlaygroundDemo } from './types/line-area/playground';
import { ChartsTypesLineAreaRangeDemo } from './types/line-area/range';
import { ChartsTypesLineAreaStackedDemo } from './types/line-area/stacked';
import { ChartsTypesLineAreaTimeSeriesDemo } from './types/line-area/time-series';
import { ChartsTypesPieDonutDemo } from './types/pie-donut';
import { ChartsTypesPieDonutDonutDemo } from './types/pie-donut/donut';
import { ChartsTypesPieDonutGaugeDemo } from './types/pie-donut/gauge';
import { ChartsTypesPieDonutPieDemo } from './types/pie-donut/pie';
import { ChartsTypesPieDonutPieNestedDemo } from './types/pie-donut/pie/nested';
import { ChartsTypesPieDonutPieNightingaleDemo } from './types/pie-donut/pie/nightingale';
import { ChartsTypesPieDonutPlaygroundDemo } from './types/pie-donut/playground';
import { ChartsTypesPolarDemo } from './types/polar';
import { ChartsTypesPolarPlaygroundDemo } from './types/polar/playground';
import { ChartsTypesPolarPolarDemo } from './types/polar/polar';
import { ChartsTypesPolarStackedDemo } from './types/polar/stacked';
import { ChartsTypesRadarDemo } from './types/radar';
import { ChartsTypesRadarPlaygroundDemo } from './types/radar/playground';
import { ChartsTypesRadarRadarDemo } from './types/radar/radar';
import { ChartsTypesRadarStackedDemo } from './types/radar/stacked';
import { ChartsTypesScatterBubbleDemo } from './types/scatter-bubble';
import { ChartsTypesScatterBubbleBubbleDemo } from './types/scatter-bubble/bubble';
import { ChartsTypesScatterBubblePlaygroundDemo } from './types/scatter-bubble/playground';
import { ChartsTypesScatterBubbleScatterDemo } from './types/scatter-bubble/scatter';
import { ChartsTypesSyncedDemo } from './types/synced';
import { ChartsTypesSyncedExamplesDemo } from './types/synced/examples';
import { ChartsTypesTreemapDemo } from './types/treemap';
import { ChartsTypesTreemapPlaygroundDemo } from './types/treemap/playground';
import { ChartsTypesTreemapTreemapDemo } from './types/treemap/treemap';

export default [
    { path: '', redirectTo: 'getting-started/architecture', pathMatch: 'full' },
    { path: 'configuration/animation', component: ChartsConfigurationAnimationDemo },
    { path: 'configuration/annotation', component: ChartsConfigurationAnnotationDemo },
    { path: 'configuration/axes', component: ChartsConfigurationAxesDemo },
    { path: 'configuration/data-labels', component: ChartsConfigurationDataLabelsDemo },
    { path: 'configuration/decimation', component: ChartsConfigurationDecimationDemo },
    { path: 'configuration/export', component: ChartsConfigurationExportDemo },
    { path: 'configuration/hover', component: ChartsConfigurationHoverDemo },
    { path: 'configuration/legend', component: ChartsConfigurationLegendDemo },
    { path: 'configuration/navigator', component: ChartsConfigurationNavigatorDemo },
    { path: 'configuration/plugins', component: ChartsConfigurationPluginsDemo },
    { path: 'configuration/reference-lines-bands', component: ChartsConfigurationReferenceLinesBandsDemo },
    { path: 'configuration/title-caption', component: ChartsConfigurationTitleCaptionDemo },
    { path: 'configuration/tooltip', component: ChartsConfigurationTooltipDemo },
    { path: 'configuration/zoom-pan', component: ChartsConfigurationZoomPanDemo },
    { path: 'getting-started/architecture', component: ChartsGettingStartedArchitectureDemo },
    { path: 'getting-started/llms', component: ChartsGettingStartedLlmsDemo },
    { path: 'getting-started/setup', component: ChartsGettingStartedSetupDemo },
    { path: 'internationalization/locale', component: ChartsInternationalizationLocaleDemo },
    { path: 'internationalization/rtl', component: ChartsInternationalizationRtlDemo },
    { path: 'reference/accessibility', component: ChartsReferenceAccessibilityDemo },
    { path: 'reference/api', component: ChartsReferenceApiDemo },
    { path: 'reference/performance', component: ChartsReferencePerformanceDemo },
    { path: 'reference/responsive', component: ChartsReferenceResponsiveDemo },
    { path: 'reference/theming', component: ChartsReferenceThemingDemo },
    { path: 'reference/tree-shaking', component: ChartsReferenceTreeShakingDemo },
    { path: 'types/candlestick', component: ChartsTypesCandlestickDemo },
    { path: 'types/candlestick/candlestick', component: ChartsTypesCandlestickCandlestickDemo },
    { path: 'types/candlestick/hollow', component: ChartsTypesCandlestickHollowDemo },
    { path: 'types/candlestick/live-data', component: ChartsTypesCandlestickLiveDataDemo },
    { path: 'types/candlestick/ohlc', component: ChartsTypesCandlestickOhlcDemo },
    { path: 'types/candlestick/playground', component: ChartsTypesCandlestickPlaygroundDemo },
    { path: 'types/column-bar', component: ChartsTypesColumnBarDemo },
    { path: 'types/column-bar/bar', component: ChartsTypesColumnBarBarDemo },
    { path: 'types/column-bar/grouped', component: ChartsTypesColumnBarGroupedDemo },
    { path: 'types/column-bar/playground', component: ChartsTypesColumnBarPlaygroundDemo },
    { path: 'types/column-bar/stacked', component: ChartsTypesColumnBarStackedDemo },
    { path: 'types/column-bar/waterfall', component: ChartsTypesColumnBarWaterfallDemo },
    { path: 'types/combo', component: ChartsTypesComboDemo },
    { path: 'types/combo/examples', component: ChartsTypesComboExamplesDemo },
    { path: 'types/heatmap', component: ChartsTypesHeatmapDemo },
    { path: 'types/heatmap/heatmap', component: ChartsTypesHeatmapHeatmapDemo },
    { path: 'types/heatmap/playground', component: ChartsTypesHeatmapPlaygroundDemo },
    { path: 'types/line-area', component: ChartsTypesLineAreaDemo },
    { path: 'types/line-area/area', component: ChartsTypesLineAreaAreaDemo },
    { path: 'types/line-area/line', component: ChartsTypesLineAreaLineDemo },
    { path: 'types/line-area/playground', component: ChartsTypesLineAreaPlaygroundDemo },
    { path: 'types/line-area/range', component: ChartsTypesLineAreaRangeDemo },
    { path: 'types/line-area/stacked', component: ChartsTypesLineAreaStackedDemo },
    { path: 'types/line-area/time-series', component: ChartsTypesLineAreaTimeSeriesDemo },
    { path: 'types/pie-donut', component: ChartsTypesPieDonutDemo },
    { path: 'types/pie-donut/donut', component: ChartsTypesPieDonutDonutDemo },
    { path: 'types/pie-donut/gauge', component: ChartsTypesPieDonutGaugeDemo },
    { path: 'types/pie-donut/pie', component: ChartsTypesPieDonutPieDemo },
    { path: 'types/pie-donut/pie/nested', component: ChartsTypesPieDonutPieNestedDemo },
    { path: 'types/pie-donut/pie/nightingale', component: ChartsTypesPieDonutPieNightingaleDemo },
    { path: 'types/pie-donut/playground', component: ChartsTypesPieDonutPlaygroundDemo },
    { path: 'types/polar', component: ChartsTypesPolarDemo },
    { path: 'types/polar/playground', component: ChartsTypesPolarPlaygroundDemo },
    { path: 'types/polar/polar', component: ChartsTypesPolarPolarDemo },
    { path: 'types/polar/stacked', component: ChartsTypesPolarStackedDemo },
    { path: 'types/radar', component: ChartsTypesRadarDemo },
    { path: 'types/radar/playground', component: ChartsTypesRadarPlaygroundDemo },
    { path: 'types/radar/radar', component: ChartsTypesRadarRadarDemo },
    { path: 'types/radar/stacked', component: ChartsTypesRadarStackedDemo },
    { path: 'types/scatter-bubble', component: ChartsTypesScatterBubbleDemo },
    { path: 'types/scatter-bubble/bubble', component: ChartsTypesScatterBubbleBubbleDemo },
    { path: 'types/scatter-bubble/playground', component: ChartsTypesScatterBubblePlaygroundDemo },
    { path: 'types/scatter-bubble/scatter', component: ChartsTypesScatterBubbleScatterDemo },
    { path: 'types/synced', component: ChartsTypesSyncedDemo },
    { path: 'types/synced/examples', component: ChartsTypesSyncedExamplesDemo },
    { path: 'types/treemap', component: ChartsTypesTreemapDemo },
    { path: 'types/treemap/playground', component: ChartsTypesTreemapPlaygroundDemo },
    { path: 'types/treemap/treemap', component: ChartsTypesTreemapTreemapDemo }
] satisfies Routes;
